before_script: cd tests

language: python

branches:
  only:
    - main
    - /^pull\//
    
python:
 - "3.8"
# - "3.9"

# Install dependencies
install:
  - pip install -r requirements_tests.txt 

# Run tests
script:
  - python paper_graphs.py 
  - python arabica_freq_unit_test.py
  - python cappuccino_unit_test.py
  - python coffee_break_unit_test.py
