before_script: cd tests

language:

branches:
  only:
    - main
    - /^pull\//
    
python:
  - 3.8
  - 3.9

# Install dependencies
install:
  - pip install -r requirements_tests.txt 

# Run tests
script:
  - python tests.py 
  # - arabica_freq_unit_test.py
